In [ ]:
from qdrant_client import QdrantClient
from qdrant_client.models import  Distance, VectorParams, PointStruct
from dotenv import load_dotenv
import os, openai

import openai
import pandas as pd

load_dotenv()  # reads .env in project root
openai.api_key = os.getenv("OPENAI_API_KEY")

In [4]:
qdrant_client = QdrantClient(url="http://localhost:6333")

qdrant_client.create_collection(
    collection_name="Amazon-items-collections-00",
    vectors_config=VectorParams(size=1536, distance=Distance.COSINE),
)

UnexpectedResponse: Unexpected Response: 409 (Conflict)
Raw response content:
b'{"status":{"error":"Wrong input: Collection `Amazon-items-collections-00` already exists!"},"time":0.003195542}'

In [5]:
df_items = pd.read_json("../notebook/meta_Electronics_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines=True)

In [6]:
df_items.head(2)

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Industrial & Scientific,"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB T...",4.4,119,[【Fast Charging Cord】These USB C cables provid...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Type-C Charger Cable ', 'url': 'ht...",RAVODOI,"[Electronics, Computers & Accessories, Compute...","{'Brand': 'RAVODOI', 'Connector Type': 'USB Ty...",B09R4Y2HKY,NaN,NaN,NaN
1,All Electronics,"SNESH-2 Pack USB-C Female to USB Male Adapter,...",4.5,352,[🔹(Light & compact) Easy to carry and light we...,[],4.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'USB Male & Female Adapter', 'url':...",SNESH,"[Electronics, Computers & Accessories, Compute...",{'Package Dimensions': '3.54 x 2.4 x 0.35 inch...,B09JV5FM2S,NaN,NaN,NaN

In [7]:
def preprocess_data(row):
    return f"{row['title']} {' '.join(row['description'])}"

In [8]:
df_items["preprocessed_data"] = df_items.apply(preprocess_data, axis=1)

In [9]:
df_items.head(2)

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,preprocessed_data
0,Industrial & Scientific,"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB T...",4.4,119,[【Fast Charging Cord】These USB C cables provid...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Type-C Charger Cable ', 'url': 'ht...",RAVODOI,"[Electronics, Computers & Accessories, Compute...","{'Brand': 'RAVODOI', 'Connector Type': 'USB Ty...",B09R4Y2HKY,NaN,NaN,NaN,"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB T..."
1,All Electronics,"SNESH-2 Pack USB-C Female to USB Male Adapter,...",4.5,352,[🔹(Light & compact) Easy to carry and light we...,[],4.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'USB Male & Female Adapter', 'url':...",SNESH,"[Electronics, Computers & Accessories, Compute...",{'Package Dimensions': '3.54 x 2.4 x 0.35 inch...,B09JV5FM2S,NaN,NaN,NaN,"SNESH-2 Pack USB-C Female to USB Male Adapter,..."

In [10]:
df_sample = df_items.sample(n=50, random_state=42)

In [11]:
def get_embedding(text, model="text-embedding-ada-002"):
    response = openai.embeddings.create(
        input=[text],
        model=model,
    )   
    return response.data[0].embedding

In [12]:
get_embedding("hi, my name is rahul")

[-0.013956214301288128,
 -0.004416482988744974,
 -0.011967037804424763,
 -0.01803690381348133,
 -0.021516362205147743,
 0.01772989332675934,
 -0.028091518208384514,
 -0.01959754340350628,
 -0.021145392209291458,
 -0.006172202993184328,
 0.022258305922150612,
 -0.019367285072803497,
 0.0032971715554594994,
 0.00244809384457767,
 -0.0016837641596794128,
 -0.027426326647400856,
 0.019815009087324142,
 -0.01796015165746212,
 0.02511095255613327,
 0.004259779583662748,
 0.0007227553869597614,
 -0.005139238201081753,
 0.022296683862805367,
 -0.0035338259767740965,
 -0.020595328882336617,
 -0.012210088782012463,
 0.02804034948348999,
 -0.012638624757528305,
 0.009044036269187927,
 -0.03348979726433754,
 -0.006463223602622747,
 -0.004908979870378971,
 -0.007815991528332233,
 -0.01569594442844391,
 0.006009103264659643,
 -0.00947257224470377,
 0.008385241031646729,
 -0.010176139883697033,
 0.012625833041965961,
 0.016565809026360512,
 0.03461550548672676,
 -0.00882656965404749,
 0.006216975394636393,
 -0.01279852632433176,
 -0.0022034444846212864,
 0.020339487120509148,
 -0.01756359450519085,
 -0.024356216192245483,
 -0.027579832822084427,
 0.01918819546699524,
 0.0155680226162076,
 -0.004000738728791475,
 -0.01999410055577755,
 -0.016527432948350906,
 -0.012440347112715244,
 0.010636656545102596,
 -0.003914392087608576,
 0.013367775827646255,
 -0.011480936780571938,
 -0.006978107150644064,
 0.030138259753584862,
 0.017665931954979897,
 -0.0093894237652421,
 0.010451170615851879,
 -0.0053567043505609035,
 0.006338500417768955,
 0.027989180758595467,
 0.004608364775776863,
 0.015248219482600689,
 0.021964088082313538,
 0.022092008963227272,
 0.03407823666930199,
 -0.016962364315986633,
 0.004032718949019909,
 0.011122757568955421,
 0.004627553280442953,
 -0.0140585508197546,
 0.002476876135915518,
 0.008692252449691296,
 -0.01100762840360403,
 0.021836167201399803,
 -0.03806937858462334,
 0.017167039215564728,
 0.007489792071282864,
 0.023473558947443962,
 0.0019284136360511184,
 -0.006850185804069042,
 0.0463075116276741,
 -0.0266587994992733,
 -0.029217226430773735,
 0.0066327196545898914,
 -0.007361871190369129,
 0.007515376433730125,
 0.029370730742812157,
 -0.026223866268992424,
 0.006907750386744738,
 -0.016923988237977028,
 0.025545883923768997,
 -0.0022658060770481825,
 -0.010336041450500488,
 0.009255106560885906,
 -0.02878229320049286,
 -0.015414517372846603,
 0.012792130000889301,
 -0.021848957985639572,
 0.00766248581930995,
 -0.013470113277435303,
 0.004378106445074081,
 0.017934566363692284,
 -0.011353015899658203,
 0.009856336750090122,
 0.029242809861898422,
 0.007508980575948954,
 -0.0326966866850853,
 -0.004039115272462368,
 -0.01698794960975647,
 -0.0024177127052098513,
 -0.013316608034074306,
 -0.023998036980628967,
 -0.01999410055577755,
 0.007182781118899584,
 -0.00023525526921730489,
 0.028245024383068085,
 -0.018650926649570465,
 0.002839852822944522,
 -0.013674787245690823,
 -0.006613531149923801,
 -0.033515382558107376,
 0.009491760283708572,
 0.002710332628339529,
 0.012018206529319286,
 -0.020134812220931053,
 -0.0001282211160287261,
 0.00018718485080171376,
 -0.012696188874542713,
 0.015990162268280983,
 -0.008762609213590622,
 0.01171119511127472,
 -0.028475282713770866,
 -0.004509225953370333,
 -0.0033291520085185766,
 0.010623863898217678,
 0.008852154016494751,
 -0.009856336750090122,
 -0.005318328272551298,
 0.013278231024742126,
 0.010137762874364853,
 0.0009825954912230372,
 0.005702091846615076,
 0.002157073002308607,
 0.0029933585319668055,
 -0.008705045096576214,
 0.014455107040703297,
 0.01982780173420906,
 -0.00020847174164373428,
 -0.0013535672333091497,
 -0.007297910284250975,
 0.031340718269348145,
 0.01641230285167694,
 -0.011065192520618439,
 0.008679460734128952,
 0.0024273067247122526,
 0.0016581799136474729,
 -0.013291023671627045,
 0.004000738728791475,
 0.033540964126586914,
 0.005510210059583187,
 -0.0029405909590423107,
 -0.026607630774378777,
 0.015376140363514423,
 0.0344364158809185,
 0.02128610387444496,
 -0.04257220774888992,
 -0.006248955614864826,
 0.014007383026182652,
 0.002006765455007553,
 0.007572941016405821,
 0.007847972214221954,
 -0.031980324536561966,
 -0.009811564348638058,
 -0.014698158018290997,
 0.003674539504572749,
 0.02422829531133175,
 0.022399019449949265,
 0.014941208064556122,
 0.011839116923511028,
 0.018970729783177376,
 -0.00682460144162178,
 0.005228783469647169,
 -0.0029070116579532623,
 0.0093894237652421,
 0.03226175159215927,
 0.019520791247487068,
 -0.0014415131881833076,
 -0.6692842841148376,
 -0.018842807039618492,
 0.010591884143650532,
 0.02470160275697708,
 0.010930875316262245,
 0.010092990472912788,
 0.004410087130963802,
 0.017589179798960686,
 -0.0029437888879328966,
 0.020902341231703758,
 -0.01251070387661457,
 0.03545978665351868,
 0.005142436362802982,
 -0.012254861183464527,
 0.0010201723780483007,
 -0.011615253984928131,
 0.007099632173776627,
 -0.020595328882336617,
 -0.02007085271179676,
 -0.014992376789450645,
 -0.009274294599890709,
 0.007272325921803713,
 -0.014403938315808773,
 0.006117836106568575,
 0.012037394568324089,
 0.0002512454229872674,
 0.01861254870891571,
 -0.011967037804424763,
 -0.017192622646689415,
 0.03162214532494545,
 -0.0281171016395092,
 0.00458917673677206,
 0.008986471220850945,
 -0.005711686331778765,
 0.03331070765852928,
 -0.019124234095215797,
 -0.0015862241853028536,
 0.01900910586118698,
 0.01648905500769615,
 0.02804034948348999,
 -0.013163101859390736,
 0.0029581801500171423,
 -0.01868930272758007,
 0.002851045923307538,
 0.009638870134949684,
 -0.004013530910015106,
 -0.0017285365611314774,
 0.0026847482658922672,
 -0.007847972214221954,
 0.0012040592264384031,
 -0.014416730962693691,
 -0.00938302744179964,
 -0.03558770567178726,
 0.0008322880021296442,
 0.015951786190271378,
 -0.0019779831636697054,
 0.0027391149196773767,
 -0.0026687581557780504,
 0.016629768535494804,
 0.018497420474886894,
 -0.00800147745758295,
 0.0055198040790855885,
 -0.02032669447362423,
 -0.00266076298430562,
 -0.012357197701931,
 -0.004090283531695604,
 -0.01495400071144104,
 -0.021989671513438225,
 0.024522513151168823,
 -0.020211566239595413,
 -0.018804430961608887,
 0.011308243498206139,
 -0.01288807112723589,
 -0.010137762874364853,
 0.015107505954802036,
 0.018548589199781418,
 0.01215252373367548,
 -0.02056974545121193,
 -0.007374662905931473,
 0.006216975394636393,
 0.009255106560885906,
 -0.006322510540485382,
 -0.012248464860022068,
 -0.014608613215386868,
 0.01385387685149908,
 -0.023870114237070084,
 -0.011308243498206139,
 -0.010393605567514896,
 -0.005599754862487316,
 -0.006818205583840609,
 0.00988192018121481,
 0.0040359171107411385,
 0.004579582717269659,
 -0.02960098907351494,
 -0.007438623812049627,
 0.019942931830883026,
 -0.018164824694395065,
 0.019930139183998108,
 0.026786720380187035,
 0.0007927123224362731,
 0.0055677746422588825,
 -0.01861254870891571,
 0.022616486996412277,
 0.01259385235607624,
 0.025251666083931923,
 0.006450431887060404,
 -0.019316116347908974,
 0.0016405907226726413,
 -0.0009642068180255592,
 -0.005890775937587023,
 0.006990899331867695,
 0.0010817345464602113,
 -0.02365264855325222,
 0.032466426491737366,
 0.010815746150910854,
 -0.031187213957309723,
 -0.002323370659723878,
 0.019725464284420013,
 0.007975893095135689,
 -0.025264456868171692,
 0.020467408001422882,
 -0.008225339464843273,
 0.011794344522058964,
 0.00554538844153285,
 -0.005254367366433144,
 0.033285122364759445,
 -0.02040344849228859,
 -0.014045759104192257,
 -0.01593899354338646,
 0.0029405909590423107,
 0.01577269658446312,
 -0.012830507010221481,
 0.006428045686334372,
 -0.012133335694670677,
 0.004122263751924038,
 -0.009242313914000988,
 0.016066916286945343,
 0.010176139883697033,
 0.0021266916301101446,
 -0.01544010080397129,
 -0.0429048053920269,
 0.008487578481435776,
 -0.0010633458150550723,
 0.0010345635237172246,
 -0.02080000378191471,
 -0.02536679431796074,
 -0.02642854116857052,
 0.0006072264513932168,
 -0.0016317961271852255,
 -0.0009929891675710678,
 -0.017832228913903236,
 0.019495205953717232,
 -0.014736534096300602,
 0.00808462593704462,
 0.019482415169477463,
 -0.017422880977392197,
 -0.010700616985559464,
 -0.012792130000889301,
 0.0018260766519233584,
 -0.03159656003117561,
 -0.00970922689884901,
 0.01868930272758007,
 -0.012740962207317352,
 0.0016741700237616897,
 0.018267162144184113,
 -0.01648905500769615,
 -0.01966150477528572,
 0.024714395403862,
 -0.0009090407402254641,
 -0.027119316160678864,
 0.0070292754098773,
 -0.007349079009145498,
 -0.006600739434361458,
 -0.007368267048150301,
 0.012632228434085846,
 0.013802708126604557,
 -0.01321427058428526,
 -0.020198773592710495,
 -0.017896190285682678,
 -0.010457566939294338,
 -0.009485364891588688,
 0.014212056994438171,
 -0.006476015783846378,
 0.008973679505288601,
 0.03024059534072876,
 0.0054174670949578285,
 -0.012651416473090649,
 0.044516611844301224,
 -0.020518576726317406,
 0.028807876631617546,
 -0.005804429296404123,
 0.008366052992641926,
 -0.034410830587148666,
 0.015631983056664467,
 -0.0021874543745070696,
 0.012299633584916592,
 0.02041623927652836,
 -0.005100862123072147,
 0.01674489863216877,
 0.018893975764513016,
 0.005184010602533817,
 0.009363839402794838,
 0.026198282837867737,
 -0.012286840938031673,
 -0.0018628539983183146,
 -0.018318330869078636,
 -0.008481182157993317,
 -0.008398033678531647,
 0.01583665795624256,
 0.025226080790162086,
 -0.01491562370210886,
 -0.021823374554514885,
 0.006741452496498823,
 -0.003214022843167186,
 0.01409692782908678,
 0.016936780884861946,
 -0.028500866144895554,
 0.0252004973590374,
 -0.027272822335362434,
 -0.0053886850364506245,
 0.024023620411753654,
 0.0153249716386199,
 -0.02152915485203266,
 -0.02348635159432888,
 0.004617959260940552,
 0.026863474398851395,
 0.019495205953717232,
 0.030752280727028847,
 0.006325708236545324,
 -0.027861259877681732,
 -0.001968389144167304,
 0.02576334960758686,
 -0.014416730962693691,
 0.019802218303084373,
 0.01459582056850195,
 0.009229522198438644,
 -0.0003795664815697819,
 -0.026223866268992424,
 0.026275034993886948,
 -0.005849201697856188,
 0.0020243546459823847,
 0.024650435894727707,
 0.033131618052721024,
 -0.01999410055577755,
 -0.006856581661850214,
 0.020339487120509148,
 0.015261011198163033,
 0.008078230544924736,
 -0.013099141418933868,
 0.043518826365470886,
 -0.013508489355444908,
 0.019469622522592545,
 0.003172448370605707,
 -0.023524727672338486,
 0.016770482063293457,
 -0.011161133646965027,
 -0.0013463717186823487,
 0.025008615106344223,
 0.021439610049128532,
 0.028347359970211983,
 -0.01894514448940754,
 0.023627065122127533,
 0.005155228544026613,
 -0.015670359134674072,
 9.474171383772045e-05,
 0.007688070181757212,
 0.00298696244135499,
 -0.0011896680807694793,
 -0.03883690759539604,
 -0.01544010080397129,
 -0.013521282002329826,
 -0.005100862123072147,
 0.00808462593704462,
 -0.02398524433374405,
 0.010342437773942947,
 0.0043845027685165405,
 0.01739729754626751,
 0.0008258919115178287,
 0.005612547043710947,
 0.004103075712919235,
 -0.007464208174496889,
 -0.005305536091327667,
 -0.0029182047583162785,
 0.012645021080970764,
 0.00039815506897866726,
 -0.014493484050035477,
 -0.03991144523024559,
 -0.009446987882256508,
 -0.023716609925031662,
 0.003290775464847684,
 0.017499634996056557,
 0.015875034034252167,
 0.021887334063649178,
 -0.010188931599259377,
 -0.0043653142638504505,
 0.015069129876792431,
 0.04835425317287445,
 0.009088808670639992,
 0.0326966866850853,
 -0.006364084780216217,
 0.013239854946732521,
 0.010400001890957355,
 -0.0041254619136452675,
 -0.01171119511127472,
 0.0060186972841620445,
 -0.003161255270242691,
 -0.027119316160678864,
 -0.0040231249295175076,
 0.023716609925031662,
 -0.012772941961884499,
 -0.012369990348815918,
 0.002369742142036557,
 -0.00800147745758295,
 0.0017141454154625535,
 -0.0011792745208367705,
 0.0033835184294730425,
 0.008903322741389275,
 -0.0009977861773222685,
 0.012139732018113136,
 -0.011039608158171177,
 0.009664454497396946,
 -0.0011736779706552625,
 -0.028091518208384514,
 -0.002552029909566045,
 0.09752719849348068,
 -0.0016645760042592883,
 -0.015951786190271378,
 0.007425831630825996,
 -0.011525709182024002,
 -0.0032492009922862053,
 -0.025878479704260826,
 -0.03456433489918709,
 0.009555721655488014,
 -0.015184259042143822,
 0.0073234946466982365,
 0.002785486401990056,
 0.004464453551918268,
 -0.002646371955052018,
 0.003917589783668518,
 -0.011346619576215744,
 0.014403938315808773,
 -0.009574909694492817,
 0.0005428660078905523,
 0.025238873437047005,
 -0.003927183803170919,
 0.010655844584107399,
 0.004240591078996658,
 0.02926839329302311,
 0.015017961151897907,
 0.020953509956598282,
 0.04876359924674034,
 0.00929987896233797,
 0.002500861417502165,
 -0.022373436018824577,
 -0.018881184980273247,
 0.009664454497396946,
 0.010745389387011528,
 -0.005574170965701342,
 -0.004237393382936716,
 0.023857323452830315,
 -0.013303815387189388,
 0.02065929025411606,
 0.00031380695872940123,
 0.0008546742028556764,
 0.020454617217183113,
 0.03031734935939312,
 -0.005708488170057535,
 -0.013163101859390736,
 -0.0028942194767296314,
 0.008046249859035015,
 -0.01820320077240467,
 0.022053632885217667,
 -0.02219434641301632,
 -0.0320059098303318,
 0.027196068316698074,
 0.011845512315630913,
 -0.02049299329519272,
 0.0004113469331059605,
 0.016872819513082504,
 0.004688315559178591,
 -0.016872819513082504,
 -0.011167529970407486,
 -0.0339503139257431,
 -0.007572941016405821,
 0.0018244775710627437,
 -0.01876605488359928,
 0.024752771481871605,
 -0.014032966457307339,
 -0.03812054917216301,
 -0.03361772000789642,
 -0.0076049212366342545,
 -0.014467899687588215,
 -0.016936780884861946,
 0.023588689044117928,
 -0.013482904992997646,
 -0.004662731662392616,
 -0.027093732729554176,
 0.006255351938307285,
 0.004995326977223158,
 -0.006533580366522074,
 0.002737515838816762,
 0.0002754305605776608,
 0.006184995174407959,
 0.005833211354911327,
 -0.014327186159789562,
 -0.03617614507675171,
 0.023703817278146744,
 0.013175894506275654,
 -0.03241525962948799,
 0.008570726960897446,
 -0.002496064407750964,
 0.01934170164167881,
 -0.009491760283708572,
 0.03699484094977379,
 -0.0016549818683415651,
 0.0038696194533258677,
 0.018996313214302063,
 0.0020051663741469383,
 -0.008641083724796772,
 0.00532152596861124,
 0.007745634764432907,
 -0.010911687277257442,
 -0.004202215000987053,
 -0.01000344567000866,
 -0.015171466395258904,
 -0.01235080137848854,
 -0.008570726960897446,
 0.0007539361831732094,
 0.0077840113081038,
 0.021887334063649178,
 -0.005785240791738033,
 0.03592030331492424,
 -0.01689840480685234,
 -0.006002706941217184,
 0.025545883923768997,
 -0.02778450772166252,
 0.022501356899738312,
 0.0102401003241539,
 0.003238007891923189,
 0.01762755587697029,
 -0.0051360405050218105,
 0.051398780196905136,
 0.00926789827644825,
 -0.012126939371228218,
 -0.01142337266355753,
 -0.020940717309713364,
 -0.008807381615042686,
 -0.007771219126880169,
 -0.0021075033582746983,
 0.006562362890690565,
 0.003313161665573716,
 -0.022232722491025925,
 0.0012656213948503137,
 -0.001324784941971302,
 0.024317840114235878,
 0.014774910174310207,
 -0.0042341952212154865,
 -0.035562120378017426,
 -0.023025834932923317,
 -0.008628292009234428,
 -0.01162165030837059,
 -0.003386716591194272,
 -0.014544651843607426,
 -0.025878479704260826,
 -0.031570978462696075,
 -0.008461994118988514,
 0.014173679985105991,
 -0.027835674583911896,
 -0.015222635120153427,
 -0.028014766052365303,
 -0.004995326977223158,
 0.013444528914988041,
 0.015785489231348038,
 0.016527432948350906,
 -0.009351047687232494,
 0.023716609925031662,
 -0.018075279891490936,
 -0.01480049453675747,
 -0.004422878846526146,
 -0.018395083025097847,
 0.019623128697276115,
 -0.01088610291481018,
 0.019853387027978897,
 0.02122214436531067,
 0.02632620371878147,
 -0.010777370072901249,
 0.01755080185830593,
 -0.011071588844060898,
 0.009293482638895512,
 0.011519312858581543,
 0.01000344567000866,
 -0.007227553520351648,
 -0.02867995575070381,
 0.019955722615122795,
 0.029319562017917633,
 -0.006370481103658676,
 0.016540223732590675,
 0.009171957150101662,
 -0.0010417591547593474,
 0.003126076888293028,
 0.020339487120509148,
 0.021900126710534096,
 -0.04909619688987732,
 -0.017704308032989502,
 -0.017921773716807365,
 0.006562362890690565,
 -0.011039608158171177,
 -0.009338255040347576,
 0.010713408701121807,
 0.008839362300932407,
 0.025481924414634705,
 -0.0021682661026716232,
 0.02536679431796074,
 0.002224231604486704,
 0.022654863074421883,
 -0.018177617341279984,
 0.002908610738813877,
 0.0031292748171836138,
 0.030419684946537018,
 -0.019930139183998108,
 -0.004870603792369366,
 -0.01439114660024643,
 0.020851172506809235,
 -0.0026815503370016813,
 0.02983124740421772,
 0.01602853834629059,
 0.007406643591821194,
 -0.003754490287974477,
 -0.008142190985381603,
 0.02421550266444683,
 -0.021081430837512016,
 -0.022654863074421883,
 0.019955722615122795,
 -0.02781009115278721,
 -0.013828292489051819,
 -0.01373874768614769,
 -0.01723099872469902,
 -0.03392472863197327,
 -0.004518819972872734,
 -0.009242313914000988,
 -0.011033212766051292,
 0.018062487244606018,
 -0.041088324040174484,
 -0.01625879667699337,
 -0.006415253505110741,
 0.012785734608769417,
 0.008673064410686493,
 0.017256584018468857,
 0.004199016839265823,
 -0.0021234937012195587,
 -0.009050432592630386,
 -0.023345638066530228,
 0.004525216296315193,
 -0.007745634764432907,
 -0.012638624757528305,
 0.00929987896233797,
 0.03430849313735962,
 -0.010400001890957355,
 -0.022795576602220535,
 0.004617959260940552,
 -0.009869128465652466,
 0.0035722022876143456,
 -0.003322755917906761,
 0.003473063465207815,
 -0.0022034444846212864,
 -0.007585733197629452,
 -0.012024602852761745,
 -0.0012496312847360969,
 -0.05047774687409401,
 0.021426817402243614,
 0.01771710067987442,
 0.012721773236989975,
 -0.038657817989587784,
 -0.029217226430773735,
 -0.01609249971807003,
 0.03484576195478439,
 -0.021337272599339485,
 -0.0016230015316978097,
 0.019380077719688416,
 -0.02154194749891758,
 -0.020365070551633835,
 -0.0030797054059803486,
 -0.02511095255613327,
 -0.008020665496587753,
 0.002299385378137231,
 0.02529004216194153,
 -0.02429225482046604,
 -0.0012416361132636666,
 0.006754244677722454,
 0.001693358295597136,
 -0.02274440787732601,
 0.013828292489051819,
 -0.016514640301465988,
 0.023268885910511017,
 -0.017781060189008713,
 -0.005359902512282133,
 0.011851908639073372,
 0.006488807965070009,
 0.00025224481942132115,
 0.014148096553981304,
 0.003792866598814726,
 -0.007943913340568542,
 0.009415008127689362,
 0.009856336750090122,
 0.01609249971807003,
 -0.018152032047510147,
 -0.009331858716905117,
 -0.008589915931224823,
 -0.00628093583509326,
 -0.02154194749891758,
 -0.02014760486781597,
 0.0017509228782728314,
 0.007867160253226757,
 -0.028091518208384514,
 -0.022092008963227272,
 -0.013559658080339432,
 -0.0008426815620623529,
 0.010214515961706638,
 0.007291514426469803,
 0.004733088426291943,
 -0.016616977751255035,
 0.006348094437271357,
 -0.03192915767431259,
 -0.013956214301288128,
 0.0071316128596663475,
 0.013559658080339432,
 -0.022974666208028793,
 0.01911144331097603,
 0.021848957985639572,
 -0.03673899918794632,
 0.003604182740673423,
 -0.025085367262363434,
 -0.03374563902616501,
 0.003002952551469207,
 0.006651907693594694,
 0.007406643591821194,
 -0.0042949579656124115,
 -0.0009082412580028176,
 0.015734320506453514,
 0.006658304017037153,
 0.01077097374945879,
 -0.01861254870891571,
 -0.030291764065623283,
 0.023192131891846657,
 -0.018919561058282852,
 0.0070292754098773,
 -0.008692252449691296,
 0.0016325956676155329,
 0.02210480161011219,
 -0.004704305902123451,
 0.02415154129266739,
 0.0026287827640771866,
 -0.02445855364203453,
 -0.010988440364599228,
 0.013163101859390736,
 0.019328908994793892,
 0.0002506457967683673,
 0.004720296245068312,
 -0.01117392536252737,
 -0.011787948198616505,

In [13]:
data_to_embed = df_sample["preprocessed_data"].to_list()
pointstruct_list = []
for i, data in enumerate(data_to_embed):
    pointstruct_list.append(
        PointStruct(id=i, vector=get_embedding(data), payload={"text": data})
    )

In [58]:
pointstruct_list

[PointStruct(id=0, vector=[-0.024218503385782242, -0.0018264788668602705, 0.015311476774513721, -0.027743641287088394, -0.005758622195571661, 0.005570255685597658, -0.022698119282722473, -0.02723236195743084, 0.007305915467441082, -0.018984615802764893, 0.0337444469332695, 0.024124320596456528, -0.02335740067064762, 0.010938690975308418, -0.009317396208643913, -0.003972507547587156, 0.002430259482935071, 0.00897430069744587, 0.020653001964092255, 0.007144458591938019, -0.01967080682516098, 0.023976318538188934, 0.0023713952396064997, -0.00722518702968955, -0.019912991672754288, -0.01107996515929699, 0.019899537786841393, -0.004520787391811609, 0.004238238092511892, -0.014302372001111507, 0.01626676134765148, 0.015217293053865433, -0.004140691366046667, -0.01449073851108551, -0.03105350397527218, 0.014948198571801186, -0.009539399296045303, -0.014786741696298122, 0.017248956486582756, 0.013750728219747543, 0.015795845538377762, 0.010945417918264866, -0.00061218993505463, 0.017195137217640877, -0.024729782715439796, -0.003318271366879344, -0.008086289279162884, 0.009552854113280773, -0.013939094729721546, 0.025833070278167725, -0.006922455504536629, 0.023128671571612358, 0.002186392666772008, -0.009351033717393875, 0.0230210330337286, -0.026882538571953773, 0.0032089517917484045, 0.012378346174955368, 0.01047450304031372, -0.03288334608078003, -0.010615777224302292, -0.011201057583093643, -0.014262007549405098, 0.0033384535927325487, 0.012102524749934673, -0.0038480511866509914, -0.01906534470617771, 0.0008560568676330149, -0.012284163385629654, 0.0008203177130781114, 0.03826523572206497, 0.010730142705142498, 0.009075211361050606, -0.006801363080739975, 0.010777234099805355, -0.01319908443838358, -0.006983002182096243, 0.009949768893420696, -0.008637933060526848, -0.0035251379013061523, 0.01237161923199892, -0.024635599926114082, 0.00775664858520031, 0.020047539845108986, -0.002904538530856371, 0.007622101344168186, 0.010622505098581314, 0.01676458679139614, 0.006421267054975033, 0.008732115849852562, 0.00504215806722641, 0.03261425346136093, 0.011544153094291687, 0.016441673040390015, -0.0010889917612075806, 0.01823115162551403, -0.0033401353284716606, 0.023653404787182808, -0.018540609627962112, -0.026115620508790016, 0.00859084166586399, 0.008456294424831867, 0.0020451180171221495, -0.014867470599710941, -0.030676770955324173, -0.0006988047389313579, 0.011826702393591404, -0.021043188869953156, 0.025119969621300697, -0.003101313952356577, -0.02055881917476654, 0.014773287810385227, 0.04039108380675316, 0.009263577871024609, 0.008066107518970966, -0.008658114820718765, 0.011153966188430786, -0.008537022396922112, 0.0068350001238286495, -0.014140915125608444, 0.018029330298304558, 0.0036159572191536427, 0.024918150156736374, -0.04324348270893097, 0.020128266885876656, 0.01914607360959053, -0.02715163305401802, -0.010878144763410091, 0.010212135501205921, 0.0012218571500852704, 0.014679104089736938, -0.008025743067264557, 0.010205408558249474, 0.00795174203813076, -0.003331726184114814, 0.004514059983193874, -0.03554738312959671, 0.0163474902510643, -0.0009250122820958495, -0.015257657505571842, 0.014544556848704815, 0.021863926202058792, 0.007749921176582575, -0.016199488192796707, -0.0119007034227252, 0.010454321280121803, -0.005576983094215393, 0.03861505910754204, 0.01338072307407856, 0.002013163175433874, -0.0015262702945619822, -0.012418710626661777, 0.0063304477371275425, 0.013791092671453953, 0.00470242602750659, -0.011402878910303116, -0.012459075078368187, -0.004026326350867748, -0.012210162356495857, -0.0376732274889946, -0.0035722292959690094, -0.0072184596210718155, -0.005398707929998636, 0.029627302661538124, 0.003160178428515792, 0.022213749587535858, 0.001316881156526506, 0.017692962661385536, 0.019980264827609062, -0.006360720843076706, -0.02072027511894703, 0.015217293053865433, -0.023061398416757584, -0.00617235479876399, 0.006872000638395548, -0.013979458250105381, 0.0018382517155259848, -0.0031366327311843634, 0.006098353769630194, 0.009694129228591919, -0.013804547488689423, 0.008153563365340233, -0.011819975450634956, 0.02534870058298111, -0.009001210331916809, -0.008920482359826565, 0.022011928260326385, -0.025563975796103477, -0.007386643905192614, -0.03492846339941025, 0.02809346467256546, 0.015728572383522987, 0.0027161724865436554, -0.009909404441714287, -0.6432434916496277, -0.019886082038283348, 0.006417903583496809, -0.003693321952596307, -0.007474099285900593, 0.001870206673629582, 0.005620711017400026, 0.004086872562766075, -0.004429968073964119, 0.009721037931740284, 0.017437322065234184, 0.004396331030875444, -0.009411579929292202, 0.020599182695150375, -0.027797460556030273, -0.028443288058042526, -0.003266134299337864, -0.0247163288295269, -0.0066600884310901165, -0.010225590318441391, -0.023613041266798973, 0.008866663090884686, -0.02244248054921627, 7.836325676180422e-05, 0.006421267054975033, -0.005556801334023476, -0.004117145668715239, -0.0003468796203378588, -0.028308739885687828, 0.03638157621026039, -0.004450150299817324, 0.03656994178891182, -0.009774857200682163, 0.012223617173731327, 0.044562045484781265, -0.030515315011143684, -0.01365654543042183, 0.03094586543738842, 0.0238014068454504, 0.02825492061674595, -0.029277481138706207, -0.0011150602949783206, 0.0024857602547854185, -0.020827913656830788, -0.004931156523525715, 0.007366461679339409, 0.02121810056269169, 0.002455487148836255, 0.005439072381705046, -0.010400502011179924, 0.0004257159016560763, -0.0020636182744055986, -0.018056239932775497, 0.014140915125608444, -0.0071646408177912235, -0.0022284386213868856, 0.024729782715439796, 0.008927209302783012, 0.013663272373378277, 0.020962459966540337, 0.0006441449513658881, 0.02063954807817936, -0.02207920327782631, -0.025550521910190582, -0.032291337847709656, 0.015298021957278252, -0.02006099373102188, -0.0031248596496880054, -0.004658698104321957, -0.02620980329811573, -0.020908642560243607, 0.005862896330654621, -0.014275462366640568, 0.0010704915039241314, 0.015688208863139153, 0.0102659547701478, 0.029519665986299515, -0.022926850244402885, -0.007716284599155188, 0.00600417098030448, 0.010393774136900902, 0.0014842243399471045, -0.02825492061674595, -0.003969143610447645, 0.038103777915239334, 0.016804950311779976, -0.01609184965491295, -0.0009292169124819338, 0.017127864062786102, -0.007070457562804222, 0.026384714990854263, 0.009310669265687466, -0.0049950662069022655, -0.026828721165657043, -0.012290890328586102, 0.006205991841852665, -0.016159124672412872, -0.003686594543978572, 0.014517647214233875, -0.007918105460703373, -0.022644301876425743, 0.02362649515271187, 0.016804950311779976, -0.006915728561580181, -0.00597726134583354, 0.02637125924229622, -0.023532312363386154, 0.002119119046255946, 0.03172624111175537, -0.00025248632300645113, -0.01130196824669838, -0.02631743997335434, -0.014221644029021263, 0.0070300935767591, -0.02147373929619789, -0.02997712604701519, 0.009176122024655342, 0.0092232134193182, 0.0009241713560186327, -0.006168991327285767, 0.021204644814133644, -0.0015918620629236102, -0.0017474322812631726, -0.007319370284676552, -0.03815759718418121, 0.0063304477371275425, 0.0006205991376191378, 0.020383907482028008, 0.014114005491137505, -0.005328070838004351, 0.014262007549405098, 0.01545947790145874, 0.012990536168217659, 0.010750324465334415, 0.005997443571686745, 0.0021224827505648136, 0.006313629448413849, -0.017531506717205048, 0.014423464424908161, -0.01956317014992237, -0.022173386067152023, 0.007090639788657427, 0.001585975638590753, -0.004413149785250425, 0.015836210921406746, -0.03683903440833092, -0.014652194455265999, -0.013871820643544197, -0.0017692962428554893, -0.0033081802539527416, -0.027057450264692307, -0.012506166473031044, -0.00511952256783843, 0.004688971675932407, 0.030380766838788986, -0.012102524749934673, -0.037135038524866104, 0.006956092547625303, -0.012331254780292511, -0.022065747529268265, -0.013730546459555626, 0.024837421253323555, -0.028308739885687828, 0.00039649390964768827, -0.01297708135098219, -0.006814817897975445, 0.02338431030511856, 0.017195137217640877, -0.004497241694480181, -0.03105350397527218, -0.007918105460703373, 0.015203838236629963, 0.006875364109873772, 0.009593218564987183, 0.006115172058343887, -0.015324930660426617, -0.01170560996979475, -0.022563572973012924, -0.00840920303016901, -0.012156343087553978, 0.00020392316218931228, -0.0026959904935210943, -0.028739292174577713, 0.0031568147242069244, 0.045476969331502914, 0.0012403574073687196, 0.02424541302025318, 0.02069336548447609, -0.0029062204994261265, 0.031268779188394547, -0.014625285752117634, -0.0007088957936502993, 0.00246221455745399, -0.004816791508346796, -0.020626092329621315, 0.011470152996480465, -0.008960846811532974, 0.01603803224861622, -0.004117145668715239, 0.024541417136788368, 0.025725433602929115, -0.00648181326687336, 0.0009409897611476481, -0.006616360507905483, 0.02573888748884201, -0.0423823818564415, 0.013178902678191662, -0.024918150156736374, 0.029438937082886696, 0.03441718593239784, -0.00574180344119668, -0.009990132413804531, -0.021837018430233, -0.00575525825843215, -0.02595416270196438, 0.0067710899747908115, 0.002857447136193514, 0.018688611686229706, 0.0006967024528421462, -0.01551329717040062, -0.0023125307634472847, 0.005997443571686745, 0.012115979567170143, 0.001823115162551403, -0.0010149907320737839, 0.03008476458489895, 0.00982194859534502, 0.011187603697180748, 0.010535049252212048, -0.021285373717546463, -0.0329640731215477, 0.013461451977491379, -0.005731712561100721, 0.002911265939474106, -0.00588644202798605, 0.03726958483457565, 0.013071265071630478, -0.000645406311377883, 0.016939498484134674, 0.0024184866342693567, 0.01697986200451851, 0.024527963250875473, -0.01009777095168829, -0.026061801239848137, -0.002672444563359022, 0.012082342058420181, 0.024218503385782242, -0.00775664858520031, 0.014854015782475471, 0.0022688028402626514, -0.005254069808870554, 0.02141992188990116, -0.01258016750216484, 0.02027626894414425, 0.015351840294897556, -0.024756692349910736, 0.03169932961463928, 0.01737004891037941, -0.00015525490744039416, 0.021258464083075523, -0.015795845538377762, -0.00722518702968955, 0.0011116965906694531, -0.014167824760079384, -0.004651971161365509, 0.014638740569353104, 0.009990132413804531, -0.003008812665939331, -0.018352244049310684, 0.007198277395218611, 0.02024935930967331, 0.007433735299855471, 0.011752701364457607, -0.013266358524560928, -0.0019778443966060877, -0.0071713682264089584, 0.0340135432779789, 0.008012288250029087, 0.01590348407626152, 0.025617795065045357, -0.010837780311703682, -0.0298156701028347, 0.0032863165251910686, -0.00025311700301244855, 0.0023293490521609783, -0.0086312061175704, -0.002495851367712021, -0.02634434960782528, -0.00813338067382574, 0.028335649520158768, 0.0014800196513533592, 0.03188769519329071, 0.004880701191723347, 0.012956899590790272, -0.011207785457372665, -0.04902901500463486, 0.03212988004088402, -0.015916939824819565, 0.018944252282381058, 0.007090639788657427, -0.020235905423760414, 0.004688971675932407, -0.013178902678191662, -0.023814862594008446, 0.022617392241954803, 0.026169439777731895, -0.032398976385593414, -0.015997666865587234, -0.00040238036308437586, -0.003378817578777671, 0.0144503740593791, -0.01985917240381241, 0.006512086372822523, -0.007702829781919718, -0.010857963003218174, 0.0046822442673146725, 0.0007950901053845882, -0.020155176520347595, 0.035036101937294006, -0.004419876728206873, -0.03753868117928505, -0.006653361022472382, -0.007157913409173489, 0.013898730278015137, 0.06474413722753525, 0.033340808004140854, 0.011147239245474339, 0.03212988004088402, -0.025752343237400055, 0.005405435338616371, -0.010191953741014004, -0.017666053026914597, 0.02728618122637272, -0.003824505489319563, -0.006956092547625303, -0.0063842665404081345, 0.01776023581624031, -0.031134232878684998, 0.019818808883428574, -0.011611427180469036, 0.016778040677309036, -0.006649997550994158, 0.021675560623407364, 0.0009729447774589062, 0.007662465330213308, 0.01889043301343918, 0.034067362546920776, -0.0035823204088956118, 0.01933443918824196, -0.0067239985801279545, 0.015970757231116295, 0.02255011722445488, 0.014880925416946411, -0.00576871307566762, 0.0065591782331466675, -0.005085885990411043, 0.001290812622755766, -0.014611830934882164, -0.01980535499751568, 0.02362649515271187, 0.028793109580874443, 0.025671614333987236, 0.007749921176582575, 0.014894380234181881, 0.04009507969021797, 0.018190788105130196, 0.025362156331539154, -0.024339595809578896, -0.0051767053082585335, 0.020545363426208496, -0.03471319004893303, -0.0061118085868656635, 0.001850024564191699, -0.022334842011332512, 0.015970757231116295, 0.013414360582828522, -0.004473695997148752, 0.026034891605377197, 0.004228147212415934, 0.03089204803109169, -0.024057047441601753, -0.019159527495503426, 0.02479705773293972, -0.02828183025121689, 0.009909404441714287, -0.014921288937330246, 0.007877741008996964, 0.018527155742049217, -0.011180875822901726, -0.024205049499869347, 1.7514792489237152e-05, -0.01867515780031681, -0.01859442889690399, -0.040848542004823685, -0.00792483240365982, -0.00020655104890465736, -0.0025900343898683786, 0.0014850652078166604, 0.02748800255358219, 0.015392204746603966, 0.0071646408177912235, -0.011409605853259563, -0.006158899981528521, 0.04324348270893097, 0.027380364015698433, -0.0034393640235066414, 0.009620128199458122, -0.00814683549106121, 0.0326949805021286, 0.01786787435412407, 0.004147418774664402, -0.002317576203495264, 0.018083149567246437, -0.006216082721948624, 0.00599071616306901, -0.02351885847747326, 0.01964389719069004, -0.03441718593239784, -0.004796609282493591, -0.030596043914556503, 0.024918150156736374, 0.024164684116840363, -0.01964389719069004, 0.00596380652859807, 0.021958110854029655, -0.030273130163550377, -0.0032224063761532307, -0.015607479959726334, 0.008981028571724892, 0.0007627147133462131, 0.009014665149152279, -0.006404448766261339, -0.03743104264140129, 0.01626676134765148, 0.0071646408177912235, -0.016858769580721855, 0.017598779872059822, -0.020827913656830788, 0.003666412318125367, 0.0074471901170909405, -0.021433375775814056, -0.002699353964999318, -0.003851414890959859, -0.012788715772330761, -0.024649055674672127, -0.04348566755652428, 0.02121810056269169, -0.005381889641284943, -0.014531102031469345, 0.03495537489652634, -0.010144862346351147, -0.026088710874319077, -0.013225994072854519, 0.03390590474009514, -0.01408709678798914, 0.026747992262244225, -0.013219267129898071, 0.002114073606207967, -0.038103777915239334, 0.003996053244918585, -0.014854015782475471, 0.022926850244402885, 0.004073417745530605, -0.01603803224861622, -0.042570747435092926, -0.009593218564987183, 0.021863926202058792, -0.005957079119980335, -0.0012260617222636938, -0.029734941199421883, -0.03350226208567619, 0.02817419357597828, -0.020895186811685562, 0.0013875184813514352, -0.006740816868841648, 0.00840920303016901, -0.02534870058298111, -0.0071108220145106316, -0.03492846339941025, -0.007379916496574879, -0.005613983608782291, -0.020922096446156502, 0.011530699208378792, 0.052069783210754395, 0.026142530143260956, 0.023128671571612358, -0.005260797217488289, 0.013670000247657299, -0.008577386848628521, 0.01919989101588726, -0.012297618202865124, -0.01087141688913107, -0.04975556954741478, 0.025725433602929115, -0.009949768893420696, -0.022092657163739204, 0.009747947566211224, -0.01407364197075367, -0.02806655503809452, -0.0002575318212620914, -0.0012126070214435458, -0.001469087670557201, -0.0009906040504574776, -0.04588061198592186, 0.005418890155851841, -0.023707224056124687, -0.004567878786474466, -0.002482396550476551, -0.033260077238082886, 0.0008140107966028154, 0.013360541313886642, 0.01606494002044201, 0.0011175830150023103, 0.0025849889498203993, 0.021648650988936424, -0.013858365826308727, 0.03460555151104927, 0.012169797904789448, 0.020235905423760414, 0.016939498484134674, -0.001580930082127452, -0.027245817705988884, -0.01593039371073246, 0.026909448206424713, 0.003205588087439537, 0.016778040677309036, -0.026007981970906258, 0.01410055160522461, -0.01906534470617771, 0.007373189087957144, -0.013447997160255909, 0.020760640501976013, -0.004154146183282137, -0.015042382292449474, 0.007971923798322678, -0.030622953549027443, -0.008779207244515419, -0.02285957708954811, 0.008563932031393051, 0.02676144614815712, -0.008126653730869293, 0.010790688917040825, -0.019415168091654778, -0.030273130163550377, 0.012391800992190838, -0.020706821233034134, 0.03627393767237663, -0.004756245296448469, -0.012761806137859821, 0.04711844399571419, 0.03587029501795769, -0.012102524749934673, -0.008738843724131584, -0.015136565081775188, -0.006562541704624891, 0.005600528791546822, 0.03538592532277107, -0.0030458131805062294, -0.013111628592014313, 0.014235098846256733, -0.00688545498996973, -0.01315871998667717, -0.024554872885346413, 0.0007828967645764351, -0.003918688278645277, 0.0012756760697811842, -0.02524106204509735, -0.029627302661538124, -0.028685472905635834, 0.012068888172507286, -0.0037706864532083273, 0.004981611855328083, 0.004271875135600567, 0.00818719994276762, -0.0329640731215477, 0.04189801216125488, -0.009922859258949757, -0.0037370496429502964, 0.016683857887983322, 3.450400981819257e-05, -0.0019559806678444147, -0.005526528228074312, 0.0040128715336322784, -0.010575413703918457, 0.007151186000555754, 0.019684262573719025, -0.0052305241115391254, 0.008806116878986359, 0.018742430955171585, -0.014275462366640568, -0.004608243238180876, 0.014262007549405098, 0.0013421087060123682, 0.021379556506872177, -0.0058998968452215195, -0.018688611686229706, -0.009229941293597221, -0.003659685142338276, -0.00010411644325358793, -0.023680314421653748, -0.00959994550794363, -0.009263577871024609, -0.02801273576915264, 0.011308696120977402, 0.008772480301558971, -0.009593218564987183, -0.024998877197504044, -0.03681212663650513, -0.015338385477662086, -0.019980264827609062, -0.004941247403621674, 0.012533076107501984, 0.016993317753076553, -0.028335649520158768, -0.007231914438307285, 0.0039018699899315834, -0.0021208010148257017, -0.0029734941199421883, 0.022348297759890556, -0.007083912380039692, 0.006357357371598482, 0.047199174761772156, -0.007036820985376835, -0.006969547364860773, 0.017491141334176064, 0.015163474716246128, -0.008456294424831867, 0.003999416716396809, -0.0024773511104285717, -0.009936314076185226, 0.01401982270181179, -0.012196707539260387, -0.03533210605382919, -0.009895949624478817, -0.01720859296619892, 0.0010763779282569885, -0.006872000638395548, 0.0340135432779789, -0.0014034959021955729, 0.0012235390022397041, 0.005509709473699331, -0.004692335147410631, -0.012667623348534107, -0.009256849996745586, 0.0009620127966627479, 0.006088262889534235, 0.022751938551664352, -0.0005049726460129023, -0.005778803955763578, -0.019132617861032486, 0.013730546459555626, -0.015890030190348625, -0.030353859066963196, 0.006814817897975445, -0.009559581987559795, 0.01676458679139614, -0.018554065376520157, -0.006845091003924608, 0.010400502011179924, 0.03293716534972191, -0.009552854113280773, -0.0016137260245159268, 0.004150782246142626, -0.004776427056640387, 0.0031315870583057404, 0.0047360630705952644, -0.005469345487654209, 0.007198277395218611, 0.012788715772330761, -0.018083149567246437, 0.006579359993338585, -0.02150064893066883, -0.03395972400903702, 0.0007576691568829119, -0.0013841547770425677, 0.03280261904001236, 0.0065591782331466675, 0.004221419803798199, -0.0481410026550293, -0.009256849996745586, -0.03826523572206497, -0.04012198746204376, -0.03853433206677437, 0.004588061012327671, 0.003713503945618868, 0.015324930660426617, 0.017800601199269295, 0.01297708135098219, 0.005906623788177967, 0.01403327751904726, -0.02828183025121689, -0.03595102205872536, -0.013649817556142807, -0.012849261984229088, -0.015298021957278252, -0.011577790603041649, -0.024662509560585022, -0.0245

In [14]:
qdrant_client.upsert(collection_name="Amazon-items-collections-00", wait=True, points=pointstruct_list)

UpdateResult(operation_id=1, status=<UpdateStatus.COMPLETED: 'completed'>)

In [15]:
def retrieve_data(query):
    query_embedding = get_embedding(query)
    results = qdrant_client.search(
        collection_name="Amazon-items-collections-00",
        query_vector=query_embedding,
        limit=5,
    )
    return results

In [17]:
retrieve_data("WiFi Range Extender").points

/var/folders/q4/llynm5vn2t38psmszbvhc82r0000gn/T/ipykernel_24709/665691538.py:3: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  results = qdrant_client.search(

AttributeError: 'list' object has no attribute 'points'